### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by ddachille23** [stat231-f21/blog_data-diggers#1]
1. Do you plan for your final project to be an extension of the mid-semester project?
* We plan on continuing to work with our Kickstarter data from the mid-semester project, providing more in-depth analysis. Our wrangled dataset currently has about 35,000 Kickstarter campaigns, but we would like to include more data in order to allow for more granular analysis. While our Shiny app provides some really cool insights on the Kickstarter dataset, we think that we can dig even deeper to find more insights. We plan on extending our Shiny app project by creating an interactive choropleth, making a summary table, doing text analysis, and possibly making a logistic regression/ML model if time permits.

2. Deliverables
* Choropleth: Embedded shiny app
   * An interactive map of the US where the user selects a project category and can hover over each state to see the success rate for that category in that state. 
   *Our map will help answer the question: How do campaign success rates differ for a particular category (or all) across the US states? 
* Summary Table: Embedded shiny app
   * A summary table to complement the map where the user can select a state and view a table of the categories ranked by success rate in that state.
* Text Analysis: Embedded shiny app
   * Word cloud by category by success rate (user selects category)
   * Does the word choice differ between successful and unsuccessful campaigns in the same category?
   * What’s the best way to describe a Kickstarter project?
* Predictive Models (if time permits):
   * Can we predict whether a campaign will be successful based on some predictors in our dataset (binary outcome S/F)?
      * Logistic regression and/or XGBoost ML model
      * Possible predictors: category, subcategory, campaign length, country, state, launch day, launch time, blurb positivity, blurb length, title length
      * May use an automated selection procedure such as best subsets, stepwise regression … etc. 
* Additional Graphs (if time permits): 
   * Correlation between sentiment in blurb and success rate
      * Is a more positive sentiment correlated with a higher success rate?
   * Faceted histogram of funding for each category to explore skewness in the data
Scatterplot of campaign length vs. success rate/bar graph of success rate for various campaign lengths 

3. Outlined Schedule 
* Before the presentation: 
   * By Nov 5th: Have updated our dataset with more Kickstarter campaigns and wrangled the dataset to prepare for the types of models or visuals we intend to include in our final project. We will also create a separate data frame to prepare for the Text Analysis. 
   * By Nov. 9th (Status Update 1): Have created the choropleth map (Karla + Dan) and the summary table (Dan) in a Shiny app 
   * By Nov. 16th (Status Update 2): Have created the text analysis visualization and analysis. 
      * Checkpoint here: Have we met our deadlines and can we continue with the rest of our ideas? If not, we can skip the model and do some additional graphs to analyze. 
   * By Nov 20th: Complete our logistic regression model. 
   * By Nov. 24rd: Finish any additional graphs and have all coding parts done. 
   * By Nov 28th: (During break) Complete our respective blog parts.
   * Nov 29th: Convene to put everything together in the blog and prepare for our presentation.
   * Nov 30th: Present.
* After the presentation: 
   * By Dec 5th: Clean up the Shiny App, visualizations, models, etc.
   * By Dec. 8th: Complete finishing touches on the blog. Make everything visually appealing and easy to read. Submit the reflection.

**Comment by bebailey** [comment]
This sounds like a good plan. You probably have more than enough on your plate with the first three deliverables, so I would encourage you to focus on those and getting a solid post out of that (and perhaps give yourselves some time to rest over Thanksgiving break!). Also, think carefully about how you are going to split the data wrangling, map, and text analysis. Are you splitting tasks, time spent on tasks, working together for chunks of time and taking turns coding vs. guiding the coding? There are a lot of ways to approach it. (No need to respond, just make sure you are talking about these things with each other.)

**Comment by bebailey** [comment]
To embed a shiny app, you can use a code chunk (see [this link](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) for details):

```
knitr::include_app("https://your-account.shinyapps.io/your-app/", height = "600px")
```

**Comment by KarlaM315** [comment]
**Update 1**: Because both of us became ill, we did not complete all that we wanted to get done by this time. So far, we have wrangled 171,000 Kickstarter campaigns to a csv file. This required some adjustments to our file management and wrangling code in our wrangling script. The raw data file is 1.16GB and the csv is over 100MB, which both exceed Github’s file size limit. We would like to get some assistance using git LFS to track the large files. At the moment, we are trying to figure out how our schedule will work now that we are a bit behind. We plan on getting our Shiny App done by Saturday and then figure out the schedule from there.

**Comment by ddachille23** [comment]
Update 2: We created our shiny app’s for the choropleth map and the table but we still need to put it all together and fix any minor details and visuals (formatting, colors, etc.). We will clean up the visuals in the end once we complete all of the major components of our project. This week we had some R Studio and Github issues related to git LFS but now that we’ve sorted those issues out we can keep moving forward. Next, we will start planning the text analysis portion of our project and hopefully complete it by the end of the week.
