### ISSUE TITLE
Cover image

### ISSUE THREAD

**Issue by bebailey** [stat231-f21/blog_data-diggers#2]
I'll use the first paragraph (or part of the first paragraph) of your blog page in the description on the [landing page](https://stat231-f21.github.io/blogs/). Please do an initial knit of your *index.Rmd* file and commit + push both that and your *index.html* file if you haven't already.

When you are ready, please share a relevant cover image for your blog (to replace the gif I have currently on the landing page). Please do this in one of two ways: 

## Option 1 for sharing cover image: 
Share a **link** to a gif or image as a new comment on this issue. Note that you can share a link to a giphy.com gif by clicking on the desired gif, hitting the "Share" option on the gif, and then copying the gif link (it should be of the form https://media.giphy.com/media/UNIQUE-IDENTIFIER/giphy.gif, e.g., https://media.giphy.com/media/26n6Gx9moCgs1pUuk/giphy.gif)

##  Option 2 for sharing cover image:
Save (and commit + push) the image in the *img* folder of your repo with the title "cover-image.png" (or "cover-image.pdf", "cover-image.jpg", "cover-image.gif", ...). As long as the filename starts with "cover-image", we're good.

**Comment by ddachille23** [comment]
Here's a link to the gif: [(https://media.gq.com/photos/59f0aa1cf964810d9a9b8f23/master/pass/1025-KickStarterMenswear_16x9.gif)]
