### ISSUE TITLE
Suggested updates

### ISSUE THREAD

**Issue by bebailey** [stat231-f21/blog_data-diggers#3]
- [ ] Introduction should describe the purpose of the blog
- [x] Somewhere you should talk about where you got the data and provide link(s).
- [ ] Would be useful to add some (very brief) narration around what each visualization is showing and key takeaways (and how they were created for more complicated visualizations) beyond the section header and graph title. What do visitors need to know if they didn't see your presentation in class?
- [ ] Include brief summary of conclusions, major take-aways from your work (addressing purpose described in intro).
- [ ]  Add direct links to all of your data sources and any other relevant sources using the format `[display text for link](https://the-link-itself.org)`.
- [ ] The immediate question on the `gganimate()` plot is "Woah! Which year did it drop?" Would be useful to include x-axis tick marks for each year or every other year so folks can more easily follow along. 
- [ ] Seems like some of the categorical variable graphics in the EDA section are already covered in the "Project Launch Analysis" section (reads to me like that section is univariate analyses, and the next section is multivariable thinking with a logistic regression model). May be better to go ahead and include all the univariate plots and summaries in that section, and perhaps rename that section to better indicate what it's capturing. Then 
- [ ] For the model fitting, you should be able to fit the full model and then use `car::anova()` with `type = "III"` to get the Chi-squared test results for each predictor in one step (instead of doing a series of LRTs). 
- [ ] I would place final model interpretation (conclusions/take-aways) after the model evaluation.
- [ ] Can your section names be more informative of what's in them (e.g., "Text analysis of Kickstarter blurbs" rather than "Text analysis")

If you need additional time to make these changes, please respond in a new comment below requesting so and giving me a sense of how much additional time you think you need.

**Comment by ddachille23** [comment]
Since there are a lot of changes that we have to make, Karla and I would request to have until the end of finals to implement all of the changes you listed. We will definitely aim to finish it before then. Let us know if that works.

**Comment by bebailey** [comment]
Okay! Hard deadline of 5pm December 17.

**Comment by ddachille23** [comment]
Great. Thank you!
